// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACzDhRzSqXskS_B6lAdNrFYgGKevqfVic',
    appId: '1:199744419875:web:83e1a0cdc4e407555b5996',
    messagingSenderId: '199744419875',
    projectId: 'fbla-assembly',
    authDomain: 'fbla-assembly.firebaseapp.com',
    storageBucket: 'fbla-assembly.firebasestorage.app',
    measurementId: 'G-48ZC7WC2HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACzDhRzSqXskS_B6lAdNrFYgGKevqfVic',
    appId: '1:199744419875:android:81586b3777b365795b5996',
    messagingSenderId: '199744419875',
    projectId: 'fbla-assembly',
    storageBucket: 'fbla-assembly.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiNf8spN1S2llQ_yooQiDlgCMyljUJMZQ',
    appId: '1:199744419875:ios:30be4366e86328a05b5996',
    messagingSenderId: '199744419875',
    projectId: 'fbla-assembly',
    storageBucket: 'fbla-assembly.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiNf8spN1S2llQ_yooQiDlgCMyljUJMZQ',
    appId: '1:199744419875:ios:30be4366e86328a05b5996',
    messagingSenderId: '199744419875',
    projectId: 'fbla-assembly',
    storageBucket: 'fbla-assembly.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACzDhRzSqXskS_B6lAdNrFYgGKevqfVic',
    appId: '1:199744419875:web:87ff938b5ed9ccf85b5996',
    messagingSenderId: '199744419875',
    projectId: 'fbla-assembly',
    authDomain: 'fbla-assembly.firebaseapp.com',
    storageBucket: 'fbla-assembly.firebasestorage.app',
    measurementId: 'G-M3CVL77RXK',
  );

  
}